version: "3"
services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "3030:3030"             
    environment:
      - NEXT_PUBLIC_API_URL=https://server-diplom.onrender.com
